apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdftohtmlkotlin-ingress
spec:
  rules:
    - host: 202.61.205.32
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: my-app-service
                port:
                  number: 8080
