apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdftohtmlkotlin.fullname" . }}
  labels:
    {{- include "pdftohtmlkotlin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: 32579
      port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "pdftohtmlkotlin.selectorLabels" . | nindent 4 }}
